### ISSUE TITLE
Compatible to older Cloud Foundry Version?

### ISSUE THREAD

**Issue by haohaoyingxin** [cloudfoundry/app-autoscaler#383]
Hello,
Probably silly questions, but does this latest autoscaler service compatible some older CF-release, for example [https://github.com/cloudfoundry-attic/cf-release/tree/v251](url)
Thanks and Regards
HAO

**Comment by silvestre** [comment]
Unfortunately we don't have a way of determining the oldest version supported. For security reasons alone, we would suggest keeping all versions of your foundation up to date.
