### ISSUE TITLE
Support for updated multi process metrics

### ISSUE THREAD

**Issue by zrob** [cloudfoundry/app-autoscaler#466]
Howdy,

Wanted to make sure y'all are aware of some changes to how metrics are generated for multi process apps.  This could theoretically cause scaling decisions to be made based on metrics that are not relevant to the web process that is being scaled.

More info here: https://lists.cloudfoundry.org/g/cf-dev/message/8483

**Comment by qibobo** [comment]
@zrob 
We already have fix for it. 
Thanks.
