### ISSUE TITLE
Autoscaler service-binding fails with the error - The service broker returned an invalid response for the request to http://autoscalerservicebroker.xxxxx.com/v2/service_instances/xxxxxxxxxxxxxxxxxx/service_bindings/xxxxxxxxxxxxxxxxxxxxxx?accepts_incomplete=true. Status Code: 500 Internal Server Error, Body: {} 

### ISSUE THREAD

**Issue by 1kaushik1** [cloudfoundry/app-autoscaler#508]
Hello, 
We have deployed the autoscaler service with bosh DNS on one of our environments.
The deployment works good, but binding a aervice-instance to an application with the policy results in the error - **The service broker returned an invalid response for the request to http://autoscalerservicebroker.xxxxx.com/v2/service_instances/xxxxxxxxxxxxxxxxxx/service_bindings/xxxxxxxxxxxxxxxxxxxxxx?accepts_incomplete=true. Status Code: 500 Internal Server Error, Body: {}** 

on checking the apiserver logs we could see the error - **{"timestamp":"2019-07-29T14:13:06.006Z","source":"autoscaler:apiserver","text":"Input policy JSON schema structure is valid","log_level":"info","data":{"app id":"75f0f8c7-1ae3-4bbc-8f40-614e34388fe9"}}
{"timestamp":"2019-07-29T14:13:06.007Z","source":"autoscaler:apiserver","text":"Input policy JSON validated successfully. Creating policy..","log_level":"info","data":{"app id":"75f0f8c7-1ae3-4bbc-8f40-614e34388fe9"}}
{"timestamp":"2019-07-29T14:13:06.008Z","source":"autoscaler:apiserver","text":"Policy creation request received","log_level":"info","data":{"app id":"75f0f8c7-1ae3-4bbc-8f40-614e34388fe9"}}
{"timestamp":"2019-07-29T14:13:06.008Z","source":"autoscaler:apiserver","text":"Policy guid 0da95b11-4514-46e5-845e-ddf40c08ac0c","log_level":"info"}
{"timestamp":"2019-07-29T14:13:06.030Z","source":"autoscaler:apiserver","text":"Error occurred during schedule creation/update ","log_level":"error","data":{"app id":"75f0f8c7-1ae3-4bbc-8f40-614e34388fe9","error":"getaddrinfo ENOTFOUND autoscalerscheduler.service.cf.internal autoscalerscheduler.service.cf.internal:6102"}}**

Something similar was seen in the service broker logs too - **{"timestamp":"2019-07-29T13:31:05.035Z","source":"autoscaler:servicebroker","text":"Api Server response","log_level":"info","data":{"status_code":500,"response":{"error":"getaddrinfo ENOTFOUND autoscalerscheduler.service.cf.internal autoscalerscheduler.service.cf.internal:6102"}}}**

The logs are generated every time we try binding it to an instance with the -c parameter.

any ideas as to why the address is not getting resolved to its ip ?

Any suggestions or inputs will be helpful

Thanks

**Comment by cdlliuy** [comment]
@1kaushik1 , could you share your  "bosh vms -d app-autoscaler" status?  Then, furthermore,  could you ssh into the vm of "autoscalerscheduler" (scheduler or asactors" depends on your deplpyment template) , and check the logs  of "autoscalerscheduler" job?

**Comment by 1kaushik1** [comment]
Hello @cdlliuy  it seems there was a misconfiguration in our bosh-dns config section, due to which the domain name was not getting resolved.
So we made the changes and now its working :)
Thank you for your support
