### ISSUE TITLE
Schedules can not be removed in synchronization when an application is deleted directly

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/app-autoscaler#553]
**Description:**
When an application is deleted without detaching its policy:
1 operator will delete the policy from policydb
2 scheduler will try to delete the schedules and notify scalingengine. Now scalingengine returns an error when the app is not found, then scheduler fails to delete the schedules.

**Comment by qibobo** [comment]
**Description:**
When an application is deleted without detaching its policy:
1 operator will delete the policy from policydb
2 scheduler will try to delete the schedules and notify scalingengine. Now scalingengine returns an error when the app is not found, then scheduler fails to delete the schedules.

**Comment by aqan213** [comment]
The fix has already been in release 3.0.1.
