### ISSUE TITLE
As for scaling based on load, we need Auto Scalar with step up scaling and step scale down

### ISSUE THREAD

**Issue by sureshnepolian** [cloudfoundry/app-autoscaler#569]
for eg, 
when rbmq queue depth is 10k to 20k items scale app to 1 to 3.
if load still increase even after scaling to 3 and rmbq queue depth increases above 20k but less than 30k increase the app from 3 to 6. similarly bring down the app based on load as well.
This way i dont have to scale large number of apps for lesser loads to medium loads.

**Comment by cdlliuy** [comment]
@sureshnepolian ,  would you like to set steps by percentage? 
https://github.com/cloudfoundry/app-autoscaler/blob/develop/docs/policy.md

adjustment | String | true | the adjustment approach for instance count with each scaling. Support regex format ^[-+][1-9]+[0-9]*[%]?$, i.e. +5 means adding 5 instances, -50% means shrinking to the half of current size.
-- | -- | -- | --


with adjust, if the base instance number is 10, then it will increase another 5 instances when adjustment = 50%;  but when the instance number is 20, then it will increase 10 instances with a scale-out.

**Comment by cdlliuy** [comment]
@sureshnepolian , is the problem resolved?

**Comment by silvestre** [comment]
Closing this, as there is a solution but no feedback. Feel free to reopen in case there are still issues.
