### ISSUE TITLE
attach-autoscaling-policy command fails

### ISSUE THREAD

**Issue by gregsprototypes** [cloudfoundry/app-autoscaler#655]
The `attach-autoscaling-policy` command fails with the following error: 

```
Error: Error saving policy
```

This also happens when using the example policy at: https://github.com/cloudfoundry/app-autoscaler/blob/main/docs/dynamicpolicy.json

On cloud.ibm.com - the autoscaling tab for the application instance is showing this: 

![image](https://user-images.githubusercontent.com/63725720/126336176-d64d4147-6d5a-4c0d-a3ac-99fb00098949.png)

This has only started recently and we did not make any changes to our build scripts - please let me know if you need any more information!

**Comment by silvestre** [comment]
Hi @gregsprototypes,

I think this is an issue that can only be solved by IBM support, as it seems to be a problem related to the concrete installation.

Best regards,
  Silvestre

**Comment by silvestre** [comment]
@donacarr FYI

**Comment by donacarr** [comment]
Yes... we have some issue in WDC...we are investigating since yesterday

**Comment by gregsprototypes** [comment]
@donacarr @silvestre thank you! 

If there's any updates or an ETA on the fix it would be appreciated - our builds are down because of this error, so this is high impact for us.

**Comment by gregsprototypes** [comment]
Seems to working again - thanks for the quick response
