### ISSUE TITLE
Consulting query on DB connections on scaling.

### ISSUE THREAD

**Issue by i076118** [cloudfoundry/app-autoscaler#734]
Hi,
We are working on BTP CF based SaaS application which is a mutli-tenant app developed using CAP framework and we are using autoscaler with scaling rule define on high memory and CPU utilization.
While performing the load testing of our application we have found that the DB connections are exhausted and the upscaling is not getting triggered as memory & CPU utilization threshold are not met.
Therefore, I wanted to know that is there a way we can upscale/downscale on DB pool connection based rule?
Also, I wanted to know that when when an upscaling/downscaling happened doesn't it also increase/decrease the number connections available in the DB connection pool or not?
We are using SAP HANA Cloud as DB.

Thanks & Regards,
Sunny Garg

**Comment by silvestre** [comment]
Hi @i076118,

yes! You can use the custom metrics feature and periodically submit the DB connections used as a custom metric. We document this in this open-source project in https://github.com/cloudfoundry/app-autoscaler/tree/main/docs#auto-scale-your-application-with-custom-metrics

As your are using the App Autoscaler as available on SAP BTP, you can also head over to the SAP documentation for further details: https://help.sap.com/viewer/7472b7d13d5d4862b2b06a730a2df086/Cloud/en-US/87e657e691ac48ba85fd777c042afbd8.html

The App Autoscaler does only scale the number of app instances, it cannot scale other parameters.

Best regards,
  Silvestre

**Comment by i076118** [comment]
Hi @silvestre ,
Thanks for the information.
When a new app instance is created during the scaling up process, then how the DB connections are managed for the newly created instance. Will it uses the existing connections or create new connections to connect to the DB?

Thanks & Regards,
Sunny Garg
