### ISSUE TITLE
Feature Request: Being able to autoscale an app by monitoring other app's metrics

### ISSUE THREAD

**Issue by d4nielfr4nco** [cloudfoundry/app-autoscaler#741]
I'm not sure if this is available in PCF at the moment, but from what I understand, it isn't, so I'm creating this issue.

I followed the documentation to autoscale apps using custom metrics, and that worked as expected for the app that emits the custom metric. 

However, I have a use case where I have an app A that will emit custom metrics to PAS. Then, I want to bind an autoscaler to apps B, C, D, etc. so that they would read those metrics emitted by A, and each one of them would have their own rules to scale. From what I understand, this is not possible at the moment. On the other hand, since all the metrics registered in Metric Registrar are forwarded to Loggregator, wouldn't this be possible with the current architecture of PAS?

**Comment by silvestre** [comment]
Hi @d4nielfr4nco ,

as far as I know VMWare's TAS does not include the App Autoscaler developed in this repo, but includes a proprietary implementation with the same name: https://docs.pivotal.io/application-service/2-11/concepts/overview.html

Please open a feature request through VMWare's support channels if you want to see the feature you are describing in TAS.

Best regards,
  Silvestre
