### ISSUE TITLE
Getting an error during the deployment

### ISSUE THREAD

**Issue by i076118** [cloudfoundry/app-autoscaler#743]
Hi Team,
We are getting below error during the deployment in our pipeline.

```
15:51:50 Error while binding service instance "rm-autoscaler" to application "consultantProfile-integration-srv-idle": Could not bind service "rm-autoscaler" to application "consultantProfile-integration-srv-idle": 502 Bad Gateway: CF-ServiceBrokerApiAuthenticationFailed(10001): Authentication with the service broker failed. Double-check that the username and password are correct. 
```

The deployments were working fine before and no config changes are done from our side.
We have a hotfix release planned which is blocked due to this issue, therefore can you please check this issue on priority.

Thanks & Regards,
Sunny Garg

**Comment by silvestre** [comment]
Hi @i076118 ,

please report SAP-specific issues through SAP support channels.

Best regards,
  Silvestre
