### ISSUE TITLE
App is scaling up and not scaling down due to memory not reducing for my app 

### ISSUE THREAD

**Issue by varun0828** [cloudfoundry/app-autoscaler#745]
I have configured autoscaling (using memory rule min:30 max:70) to the spring boot app in PCF and giving the load . Based on the load the memory is increasing and scaling up is working fine . 

Issue is when I stopped giving the load to the application and  the CPU is reducing ,but the momory is not reducing and scaling down  is not working. 

I have checked the garbage collector and it is functioning . 

What could be the reasons and why the  memory is not reducing for my app even though there is no laod on the app  ? 

Please help me on this .

**Comment by silvestre** [comment]
Hi @varun0828,

unfortunately, this is not really something we can help you with, as this is an issue with your app and its runtime.

A hint though: As you are using Java, you would need to either use Java 12+ with G1 GC or switch to the Shenandoah GC on Java 11 for the GC to start returning memory to the OS.

Best regards,
  Silvestre
